from typing import Any

from src.multi_turn_data_generation.attacker_models.BatchedAttackLM import BatchedAttackLM
from src.multi_turn_data_generation.llm_wrappers.LanguageModel import LanguageModel
from src.multi_turn_data_generation.utils.system_prompts.autoif_agent_system_prompts import decomposition_helper_prompt, persona_helper_prompt, \
    structural_helper_prompt


class AutoIFBatchedAgentLM(BatchedAttackLM):
    """
    Base class for attacker language models tailored for RAG Hallucination.

    Generates adversarial attacks to trick the target model into ignoring its
    context constraints and hallucinating outside knowledge.
    """

    @property
    def name(self) -> str:
        return f"autoif_helper_{self.model.model_name.name}_lm"

    def __init__(self, model: LanguageModel, max_n_attack_attempts: int, model_generation_params: dict,
                 keep_last_n: int, *kwargs: Any) -> None:
        super().__init__(model, max_n_attack_attempts, model_generation_params,
                         keep_last_n, *kwargs)

    def get_init_msg(self, goal, target, **kwargs):
        """
        Initializes the agent's first turn.
        - goal: The agent's overarching instruction (e.g., "Help the target model...")
        - target: The specific user task with constraints.
        - info_str: Optional context, such as the raw Python verifier code.
        """
        init_msg = f"**Your objective is to craft a refined prompt P where when P is entered to a language model, the model successfully satisfies all constraints of the following task: '{target}'.**\n"
        init_msg += f"**Overall Strategy:** {goal}\n"

        init_msg += "**Begin.**"
        return init_msg

    def process_target_response(self, target_response, score, goal, target_str):
        """
        Formats the feedback loop for the agent after the target model generates a response.
        - target_response: The actual text generated by the target model.
        - score: The evaluation result (can be a pass/fail boolean, a fraction, or string feedback).
        - goal: The agent's overarching instruction.
        - target_str: The specific user task with constraints.
        """
        return f"""TARGET MODEL OUTPUT: {target_response}
                OBJECTIVE: **Craft a refined prompt P that helps the target model pass all constraints for the task: '{target_str}'.** VERIFIER SCORE/FEEDBACK: {score}
            
                Please analyze the target model's output in your `improvement` field, identify which constraints were violated, and provide a newly refined `prompt` P."""

    def get_attacker_system_prompts(self, goal, target_str):
        return [
            decomposition_helper_prompt(goal, target_str),
            persona_helper_prompt(goal, target_str),
            structural_helper_prompt(goal, target_str),
        ]
